services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    platform: "linux/amd64"
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./:/go/src
  db:
    image: postgres:16.3
    environment:
      POSTGRES_DB: super_shiharai_kun
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
