// Code generated by MockGen. DO NOT EDIT.
// Source: invoice_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/i0li/super_shiharai_kun/internal/domain"
)

// MockInvoiceRepository is a mock of InvoiceRepository interface.
type MockInvoiceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInvoiceRepositoryMockRecorder
}

// MockInvoiceRepositoryMockRecorder is the mock recorder for MockInvoiceRepository.
type MockInvoiceRepositoryMockRecorder struct {
	mock *MockInvoiceRepository
}

// NewMockInvoiceRepository creates a new mock instance.
func NewMockInvoiceRepository(ctrl *gomock.Controller) *MockInvoiceRepository {
	mock := &MockInvoiceRepository{ctrl: ctrl}
	mock.recorder = &MockInvoiceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoiceRepository) EXPECT() *MockInvoiceRepositoryMockRecorder {
	return m.recorder
}

// CountByPaymentDueDatePeriod mocks base method.
func (m *MockInvoiceRepository) CountByPaymentDueDatePeriod(userID int64, startDate, endDate time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByPaymentDueDatePeriod", userID, startDate, endDate)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByPaymentDueDatePeriod indicates an expected call of CountByPaymentDueDatePeriod.
func (mr *MockInvoiceRepositoryMockRecorder) CountByPaymentDueDatePeriod(userID, startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByPaymentDueDatePeriod", reflect.TypeOf((*MockInvoiceRepository)(nil).CountByPaymentDueDatePeriod), userID, startDate, endDate)
}

// Create mocks base method.
func (m *MockInvoiceRepository) Create(invoice *domain.Invoice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", invoice)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockInvoiceRepositoryMockRecorder) Create(invoice interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInvoiceRepository)(nil).Create), invoice)
}

// FindByPaymentDueDatePeriod mocks base method.
func (m *MockInvoiceRepository) FindByPaymentDueDatePeriod(userID int64, startDate, endDate time.Time, limit, offset int) ([]*domain.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPaymentDueDatePeriod", userID, startDate, endDate, limit, offset)
	ret0, _ := ret[0].([]*domain.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPaymentDueDatePeriod indicates an expected call of FindByPaymentDueDatePeriod.
func (mr *MockInvoiceRepositoryMockRecorder) FindByPaymentDueDatePeriod(userID, startDate, endDate, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPaymentDueDatePeriod", reflect.TypeOf((*MockInvoiceRepository)(nil).FindByPaymentDueDatePeriod), userID, startDate, endDate, limit, offset)
}
